<a href="https://colab.research.google.com/github/chintu4/LLM-based-Movie-Recommendation/blob/main/sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

movies = pd.read_csv("movies_with_Genre.csv")

In [20]:
movies.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,title_and_subtitle,tagged_description,simple_Genre
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,Nonfiction
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,The Batman,"In his second year of fighting crime, Batman u...",Fiction
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,No Exit,Stranded at a rest stop in the mountains durin...,Fiction
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,Encanto,"The tale of an extraordinary family, the Madri...",Fiction
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,The King's Man,As a collection of history's worst tyrants and...,Fiction

In [21]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = "cpu")
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528684265911579},
  {'label': 'neutral', 'score': 0.005764597095549107},
  {'label': 'anger', 'score': 0.004419783595949411},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611993182450533},
  {'label': 'fear', 'score': 0.0004138521908316761}]]

In [22]:
movies["Overview"][0]

'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.'

In [23]:
classifier(movies["Overview"][0])

[[{'label': 'fear', 'score': 0.926146924495697},
  {'label': 'anger', 'score': 0.024331513792276382},
  {'label': 'neutral', 'score': 0.02144639566540718},
  {'label': 'sadness', 'score': 0.018041174858808517},
  {'label': 'disgust', 'score': 0.006444456521421671},
  {'label': 'surprise', 'score': 0.0026720191817730665},
  {'label': 'joy', 'score': 0.0009175842860713601}]]

In [24]:
classifier(movies["Overview"][0].split("."))

[[{'label': 'fear', 'score': 0.5420975089073181},
  {'label': 'sadness', 'score': 0.26904430985450745},
  {'label': 'neutral', 'score': 0.11751072108745575},
  {'label': 'surprise', 'score': 0.029642924666404724},
  {'label': 'anger', 'score': 0.026007702574133873},
  {'label': 'disgust', 'score': 0.012124402448534966},
  {'label': 'joy', 'score': 0.0035724409390240908}],
 [{'label': 'fear', 'score': 0.8925904631614685},
  {'label': 'anger', 'score': 0.07944370806217194},
  {'label': 'neutral', 'score': 0.012798137031495571},
  {'label': 'disgust', 'score': 0.006753373425453901},
  {'label': 'sadness', 'score': 0.0049059572629630566},
  {'label': 'surprise', 'score': 0.002205240773037076},
  {'label': 'joy', 'score': 0.001303090830333531}],
 [{'label': 'neutral', 'score': 0.5494766235351562},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400670766830444},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136282369494438},
  {'label': 'joy', 'score': 0.04056442528963089}]]

In [25]:
sentences = movies["Overview"][0].split(".")
predictions = classifier(sentences)

In [26]:
sentences[0]

'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero'

In [27]:
predictions[0]

[{'label': 'fear', 'score': 0.5420975089073181},
 {'label': 'sadness', 'score': 0.26904430985450745},
 {'label': 'neutral', 'score': 0.11751072108745575},
 {'label': 'surprise', 'score': 0.029642924666404724},
 {'label': 'anger', 'score': 0.026007702574133873},
 {'label': 'disgust', 'score': 0.012124402448534966},
 {'label': 'joy', 'score': 0.0035724409390240908}]

In [28]:
sentences[2]

''

In [29]:
predictions[2]

[{'label': 'neutral', 'score': 0.5494766235351562},
 {'label': 'sadness', 'score': 0.11169017851352692},
 {'label': 'disgust', 'score': 0.10400670766830444},
 {'label': 'surprise', 'score': 0.07876552641391754},
 {'label': 'anger', 'score': 0.0641336739063263},
 {'label': 'fear', 'score': 0.05136282369494438},
 {'label': 'joy', 'score': 0.04056442528963089}]

In [30]:
predictions

[[{'label': 'fear', 'score': 0.5420975089073181},
  {'label': 'sadness', 'score': 0.26904430985450745},
  {'label': 'neutral', 'score': 0.11751072108745575},
  {'label': 'surprise', 'score': 0.029642924666404724},
  {'label': 'anger', 'score': 0.026007702574133873},
  {'label': 'disgust', 'score': 0.012124402448534966},
  {'label': 'joy', 'score': 0.0035724409390240908}],
 [{'label': 'fear', 'score': 0.8925904631614685},
  {'label': 'anger', 'score': 0.07944370806217194},
  {'label': 'neutral', 'score': 0.012798137031495571},
  {'label': 'disgust', 'score': 0.006753373425453901},
  {'label': 'sadness', 'score': 0.0049059572629630566},
  {'label': 'surprise', 'score': 0.002205240773037076},
  {'label': 'joy', 'score': 0.001303090830333531}],
 [{'label': 'neutral', 'score': 0.5494766235351562},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400670766830444},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136282369494438},
  {'label': 'joy', 'score': 0.04056442528963089}]]

In [31]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.026007702574133873},
 {'label': 'disgust', 'score': 0.012124402448534966},
 {'label': 'fear', 'score': 0.5420975089073181},
 {'label': 'joy', 'score': 0.0035724409390240908},
 {'label': 'neutral', 'score': 0.11751072108745575},
 {'label': 'sadness', 'score': 0.26904430985450745},
 {'label': 'surprise', 'score': 0.029642924666404724}]

In [32]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [33]:
for i in range(10):
    isbn.append(movies["Title"][i])
    sentences = movies["Overview"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [34]:
emotion_scores

{'anger': [np.float64(0.07944370806217194),
  np.float64(0.18817979097366333),
  np.float64(0.0641336739063263),
  np.float64(0.0641336739063263),
  np.float64(0.24245001375675201),
  np.float64(0.13221576809883118),
  np.float64(0.12618204951286316),
  np.float64(0.7532297968864441),
  np.float64(0.0641336739063263),
  np.float64(0.3216216266155243)],
 'disgust': [np.float64(0.10400670766830444),
  np.float64(0.4141809344291687),
  np.float64(0.10400670766830444),
  np.float64(0.10400670766830444),
  np.float64(0.206266388297081),
  np.float64(0.10400670766830444),
  np.float64(0.16331978142261505),
  np.float64(0.21924945712089539),
  np.float64(0.10400670766830444),
  np.float64(0.1174505427479744)],
 'fear': [np.float64(0.8925904631614685),
  np.float64(0.1439974159002304),
  np.float64(0.9870162606239319),
  np.float64(0.9570924639701843),
  np.float64(0.13970623910427094),
  np.float64(0.9441531300544739),
  np.float64(0.6155821084976196),
  np.float64(0.9719827771186829),
  np.float64(0.7786306738853455),
  np.float64(0.45190998911857605)],
 'joy': [np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.8767201900482178),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04056442528963089),
  np.float64(0.04780619591474533)],
 'sadness': [np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.6989275813102722),
  np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.9416287541389465),
  np.float64(0.4304485023021698)],
 'surprise': [np.float64(0.26904430985450745),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.12532904744148254)],
 'neutral': [np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.15599460899829865),
  np.float64(0.07876552641391754),
  np.float64(0.48838475346565247),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.19071893393993378)]}

In [35]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(movies))):
    isbn.append(movies["Title"][i])
    sentences = movies["Overview"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 8170/8170 [26:43<00:00,  5.10it/s]

In [36]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["Title"] = isbn

In [37]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,Title
0,0.079444,0.104007,0.892590,0.040564,0.549477,0.269044,0.078766,Spider-Man: No Way Home
1,0.188180,0.414181,0.143997,0.040564,0.549477,0.111690,0.078766,The Batman
2,0.064134,0.104007,0.987016,0.040564,0.549477,0.111690,0.078766,No Exit
3,0.064134,0.104007,0.957092,0.876720,0.698928,0.111690,0.155995,Encanto
4,0.242450,0.206266,0.139706,0.040564,0.549477,0.111690,0.078766,The King's Man
...,...,...,...,...,...,...,...,...
8165,0.091837,0.884995,0.051363,0.040564,0.549477,0.111690,0.078766,Badlands
8166,0.064134,0.966929,0.051363,0.087916,0.853928,0.111690,0.078766,Violent Delights
8167,0.064134,0.163012,0.372127,0.040564,0.549477,0.902290,0.078766,The Offering
8168,0.233351,0.539062,0.063693,0.322472,0.847774,0.074020,0.038100,The United States vs. Billie Holiday
8169,0.064134,0.104007,0.397736,0.040564,0.549477,0.111690,0.078766,Threads

In [38]:
movies = pd.merge(movies, emotions_df, on = "Title")

In [39]:
movies

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,title_and_subtitle,tagged_description,simple_Genre,anger,disgust,fear,joy,sadness,surprise,neutral
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,Nonfiction,0.079444,0.104007,0.892590,0.040564,0.549477,0.269044,0.078766
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,The Batman,"In his second year of fighting crime, Batman u...",Fiction,0.188180,0.414181,0.143997,0.040564,0.549477,0.111690,0.078766
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...,No Exit,Stranded at a rest stop in the mountains durin...,Fiction,0.064134,0.104007,0.987016,0.040564,0.549477,0.111690,0.078766
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...,Encanto,"The tale of an extraordinary family, the Madri...",Fiction,0.064134,0.104007,0.957092,0.876720,0.698928,0.111690,0.155995
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...,The King's Man,As a collection of history's worst tyrants and...,Fiction,0.242450,0.206266,0.139706,0.040564,0.549477,0.111690,0.078766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8665,1973-10-15,Badlands,A dramatization of the Starkweather-Fugate kil...,13.357,896,7.6,en,"Drama, Crime",https://image.tmdb.org/t/p/original/z81rBzHNgi...,Badlands,A dramatization of the Starkweather-Fugate kil...,Fiction,0.091837,0.884995,0.051363,0.040564,0.549477,0.111690,0.078766
8666,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...,Violent Delights,A female vampire falls in love with a man she ...,Fiction,0.064134,0.966929,0.051363,0.087916,0.853928,0.111690,0.078766
8667,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...,The Offering,When young and successful reporter Jamie finds...,Fiction,0.064134,0.163012,0.372127,0.040564,0.549477,0.902290,0.078766
8668,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,Nonfiction,0.233351,0.539062,0.063693,0.322472,0.847774,0.074020,0.038100
8669,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...,Threads,Documentary style account of a nuclear holocau...,Nonfiction,0.064134,0.104007,0.397736,0.040564,0.549477,0.111690,0.078766

In [40]:
movies.to_csv("movies_with_emotions.csv", index = False)

In [41]:
from google.colab import files

# This will trigger a browser download of the generated file
files.download('movies_with_emotions.csv')